from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from portal import views

urlpatterns = [
    path("admin/", views.admin_panel_redirect, name="admin_panel_redirect"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.sign_up, name="signup"),
    path("register/", views.sign_up, name="register"),
    path("showcase/", views.system_showcase, name="showcase"),
    path("", views.dashboard, name="dashboard"),
    path("student/id/", views.digital_id, name="digital_id"),
    path("student/calendar/", views.event_calendar, name="event_calendar"),
    path("student/activities/", views.my_activities, name="my_activities"),
    path("student/clearance/", views.clearance, name="clearance"),
    path("announcements/", views.announcements, name="announcements"),
    path("officer/", views.officer_dashboard, name="officer_dashboard"),
    path("officer/events/", views.events_manage, name="events_manage"),
    path("officer/events/new/", views.event_create, name="event_create"),
    path("officer/events/<int:event_id>/edit/", views.event_edit, name="event_edit"),
    path("officer/events/<int:event_id>/delete/", views.event_delete, name="event_delete"),
    path("officer/scanner/", views.scanner, name="scanner"),
    path("officer/scanner/scan/", views.scan_attendance, name="scan_attendance"),
    path("officer/attendance/", views.attendance_records, name="attendance_records"),
    path("officer/attendance/add/", views.attendance_create, name="attendance_create"),
    path("officer/attendance/<int:record_id>/status/", views.attendance_update_status, name="attendance_update_status"),
    path("officer/attendance/<int:record_id>/delete/", views.attendance_delete, name="attendance_delete"),
    path("officer/fines/", views.fines, name="fines"),
    path("officer/fines/new/", views.fine_create, name="fine_create"),
    path("officer/fines/<int:fine_id>/edit/", views.fine_edit, name="fine_edit"),
    path("officer/fines/<int:fine_id>/delete/", views.fine_delete, name="fine_delete"),
    path("officer/clearance/", views.clearance_manage, name="clearance_manage"),
    path("officer/announcements/", views.announcement_manage, name="announcement_manage"),
    path("officer/announcements/new/", views.announcement_create, name="announcement_create"),
    path("officer/announcements/<int:announcement_id>/edit/", views.announcement_edit, name="announcement_edit"),
    path("officer/announcements/<int:announcement_id>/delete/", views.announcement_delete, name="announcement_delete"),
    path("officer/reports/", views.reports, name="reports"),
    path("officer/reports/excel/", views.report_excel, name="report_excel"),
    path("officer/reports/pdf/", views.report_pdf, name="report_pdf"),
    path("admin/users/", views.user_manage, name="user_manage"),
    path("admin/users/<int:user_id>/edit/", views.user_edit, name="user_edit"),
    path("admin/users/<int:user_id>/promote/", views.user_promote, name="user_promote"),
    path("admin/users/<int:user_id>/demote/", views.user_demote, name="user_demote"),
    path("admin/users/<int:user_id>/role-request/", views.user_role_request, name="user_role_request"),
    path("admin/users/<int:user_id>/delete/", views.user_delete, name="user_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
